<?php

namespace App\Enums\Billing;

use Filament\Support\Contracts\HasLabel;

enum TaxIdType: string implements HasLabel
{
    case AdNrt = 'ad_nrt';
    case AeTrn = 'ae_trn';
    case AlTin = 'al_tin';
    case AmTin = 'am_tin';
    case AoTin = 'ao_tin';
    case ArCuit = 'ar_cuit';
    case AuAbn = 'au_abn';
    case AuArn = 'au_arn';
    case AwTin = 'aw_tin';
    case AzTin = 'az_tin';
    case BaTin = 'ba_tin';
    case BbTin = 'bb_tin';
    case BdBin = 'bd_bin';
    case BfIfu = 'bf_ifu';
    case BgUic = 'bg_uic';
    case BhVat = 'bh_vat';
    case BjIfu = 'bj_ifu';
    case BoTin = 'bo_tin';
    case BrCnpj = 'br_cnpj';
    case BrCpf = 'br_cpf';
    case BsTin = 'bs_tin';
    case ByTin = 'by_tin';
    case CaBn = 'ca_bn';
    case CaGstHst = 'ca_gst_hst';
    case CaPstBc = 'ca_pst_bc';
    case CaPstMb = 'ca_pst_mb';
    case CaPstSk = 'ca_pst_sk';
    case CaQst = 'ca_qst';
    case CdNif = 'cd_nif';
    case ChUid = 'ch_uid';
    case ChVat = 'ch_vat';
    case ClTin = 'cl_tin';
    case CmNiu = 'cm_niu';
    case CnTin = 'cn_tin';
    case CoNit = 'co_nit';
    case CrTin = 'cr_tin';
    case CvNif = 'cv_nif';
    case DeStn = 'de_stn';
    case DoRcn = 'do_rcn';
    case EcRuc = 'ec_ruc';
    case EgTin = 'eg_tin';
    case EsCif = 'es_cif';
    case EtTin = 'et_tin';
    case EuOssVat = 'eu_oss_vat';
    case EuVat = 'eu_vat';
    case GbVat = 'gb_vat';
    case GeVat = 'ge_vat';
    case GnNif = 'gn_nif';
    case HkBr = 'hk_br';
    case HrOib = 'hr_oib';
    case HuTin = 'hu_tin';
    case IdNpwp = 'id_npwp';
    case IlVat = 'il_vat';
    case InGst = 'in_gst';
    case IsVat = 'is_vat';
    case JpCn = 'jp_cn';
    case JpRn = 'jp_rn';
    case JpTrn = 'jp_trn';
    case KePin = 'ke_pin';
    case KgTin = 'kg_tin';
    case KhTin = 'kh_tin';
    case KrBrn = 'kr_brn';
    case KzBin = 'kz_bin';
    case LaTin = 'la_tin';
    case LiUid = 'li_uid';
    case LiVat = 'li_vat';
    case MaVat = 'ma_vat';
    case MdVat = 'md_vat';
    case MePib = 'me_pib';
    case MkVat = 'mk_vat';
    case MrNif = 'mr_nif';
    case MxRfc = 'mx_rfc';
    case MyFrp = 'my_frp';
    case MyItn = 'my_itn';
    case MySst = 'my_sst';
    case NgTin = 'ng_tin';
    case NoVat = 'no_vat';
    case NoVoec = 'no_voec';
    case NpPan = 'np_pan';
    case NzGst = 'nz_gst';
    case OmVat = 'om_vat';
    case PeRuc = 'pe_ruc';
    case PhTin = 'ph_tin';
    case RoTin = 'ro_tin';
    case RsPib = 'rs_pib';
    case RuInn = 'ru_inn';
    case RuKpp = 'ru_kpp';
    case SaVat = 'sa_vat';
    case SgGst = 'sg_gst';
    case SgUen = 'sg_uen';
    case SiTin = 'si_tin';
    case SnNinea = 'sn_ninea';
    case SrFin = 'sr_fin';
    case SvNit = 'sv_nit';
    case ThVat = 'th_vat';
    case TjTin = 'tj_tin';
    case TrTin = 'tr_tin';
    case TwVat = 'tw_vat';
    case TzVat = 'tz_vat';
    case UaVat = 'ua_vat';
    case UgTin = 'ug_tin';
    case UsEin = 'us_ein';
    case UyRuc = 'uy_ruc';
    case UzTin = 'uz_tin';
    case UzVat = 'uz_vat';
    case VeRif = 've_rif';
    case VnTin = 'vn_tin';
    case ZaVat = 'za_vat';
    case ZmTin = 'zm_tin';
    case ZwTin = 'zw_tin';

    public function getLabel(): string
    {
        return match ($this) {
            self::AdNrt => 'Andorra NRT',
            self::AeTrn => 'United Arab Emirates TRN',
            self::AlTin => 'Albania Tax ID',
            self::AmTin => 'Armenia Tax ID',
            self::AoTin => 'Angola Tax ID',
            self::ArCuit => 'Argentina CUIT',
            self::AuAbn => 'Australian Business Number (AU ABN)',
            self::AuArn => 'Australian Taxation Office Reference Number',
            self::AwTin => 'Aruba Tax ID',
            self::AzTin => 'Azerbaijan Tax ID',
            self::BaTin => 'Bosnia and Herzegovina Tax ID',
            self::BbTin => 'Barbados Tax ID',
            self::BdBin => 'Bangladesh BIN',
            self::BfIfu => 'Burkina Faso IFU',
            self::BgUic => 'Bulgaria UIC',
            self::BhVat => 'Bahrain VAT',
            self::BjIfu => 'Benin IFU',
            self::BoTin => 'Bolivia TIN',
            self::BrCnpj => 'Brazilian CNPJ',
            self::BrCpf => 'Brazilian CPF',
            self::BsTin => 'Bahamas Tax ID',
            self::ByTin => 'Belarus TIN',
            self::CaBn => 'Canadian BN',
            self::CaGstHst => 'Canadian GST/HST',
            self::CaPstBc => 'Canadian PST (BC)',
            self::CaPstMb => 'Canadian PST (MB)',
            self::CaPstSk => 'Canadian PST (SK)',
            self::CaQst => 'Canadian QST',
            self::CdNif => 'Democratic Republic of Congo NIF',
            self::ChUid => 'Switzerland UID',
            self::ChVat => 'Switzerland VAT',
            self::ClTin => 'Chile TIN',
            self::CmNiu => 'Cameroon NIU',
            self::CnTin => 'China TIN',
            self::CoNit => 'Colombia NIT',
            self::CrTin => 'Costa Rica TIN',
            self::CvNif => 'Cape Verde NIF',
            self::DeStn => 'Germany StN',
            self::DoRcn => 'Dominican Republic RCN',
            self::EcRuc => 'Ecuador RUC',
            self::EgTin => 'Egypt TIN',
            self::EsCif => 'Spain CIF',
            self::EtTin => 'Ethiopia TIN',
            self::EuOssVat => 'EU OSS VAT',
            self::EuVat => 'European VAT number',
            self::GbVat => 'United Kingdom VAT number',
            self::GeVat => 'Georgia VAT',
            self::GnNif => 'Guinea NIF',
            self::HkBr => 'Hong Kong BR number',
            self::HrOib => 'Croatia OIB',
            self::HuTin => 'Hungary TIN',
            self::IdNpwp => 'Indonesia NPWP',
            self::IlVat => 'Israel VAT',
            self::InGst => 'India GST',
            self::IsVat => 'Iceland VAT',
            self::JpCn => 'Japan CN',
            self::JpRn => 'Japan RN (registered foreign businesses)',
            self::JpTrn => 'Japan TRN',
            self::KePin => 'Kenya PIN',
            self::KgTin => 'Kyrgyzstan TIN',
            self::KhTin => 'Cambodia Tax ID',
            self::KrBrn => 'Korea BRN',
            self::KzBin => 'Kazakhstan BIN',
            self::LaTin => 'Laos Tax ID',
            self::LiUid => 'Liechtenstein UID',
            self::LiVat => 'Liechtenstein VAT',
            self::MaVat => 'Morocco VAT',
            self::MdVat => 'Moldova VAT',
            self::MePib => 'Montenegro PIB',
            self::MkVat => 'Macedonia VAT',
            self::MrNif => 'Mauritania NIF',
            self::MxRfc => 'Mexican RFC',
            self::MyFrp => 'Malaysia FRP',
            self::MyItn => 'Malaysia ITN',
            self::MySst => 'Malaysia SST',
            self::NgTin => 'Nigeria TIN',
            self::NoVat => 'Norway VAT',
            self::NoVoec => 'Norway VOEC',
            self::NpPan => 'Nepal PAN',
            self::NzGst => 'New Zealand GST',
            self::OmVat => 'Oman VAT',
            self::PeRuc => 'Peru RUC',
            self::PhTin => 'Philippines TIN',
            self::RoTin => 'Romania TIN',
            self::RsPib => 'Serbia PIB',
            self::RuInn => 'Russia INN',
            self::RuKpp => 'Russia KPP',
            self::SaVat => 'Saudi Arabia VAT',
            self::SgGst => 'Singapore GST',
            self::SgUen => 'Singapore UEN',
            self::SiTin => 'Slovenia TIN',
            self::SnNinea => 'Senegal NINEA',
            self::SrFin => 'Suriname FIN',
            self::SvNit => 'El Salvador NIT',
            self::ThVat => 'Thailand VAT',
            self::TjTin => 'Tajikistan TIN',
            self::TrTin => 'Turkey TIN',
            self::TwVat => 'Taiwan VAT',
            self::TzVat => 'Tanzania VAT',
            self::UaVat => 'Ukraine VAT',
            self::UgTin => 'Uganda TIN',
            self::UsEin => 'United States EIN',
            self::UyRuc => 'Uruguay RUC',
            self::UzTin => 'Uzbekistan TIN',
            self::UzVat => 'Uzbekistan VAT',
            self::VeRif => 'Venezuela RIF',
            self::VnTin => 'Vietnam TIN',
            self::ZaVat => 'South Africa VAT',
            self::ZmTin => 'Zambia TIN',
            self::ZwTin => 'Zimbabwe Tax ID',
        };
    }
}
